sonata_admin:
    title: 'Admin Dashboard'
    title_logo: build/images/logo.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: center }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
