twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/styles': styles
        '%kernel.project_dir%/public/build/images': images

when@test:
    twig:
        strict_variables: true
